on:
  push:
    branches:
    - main
jobs:
  test:
    runs-on: ubuntu-20.04
    name: test
    steps:
      - name: Update deploy_cloudflare
        # You may pin to the exact commit or the version.
        # uses: bambamboole/gha-upmerge@de87b212278009f9ace0ba024701890b9eb3281b
        uses: bambamboole/gha-upmerge@v1.0.1
        with:
          # Name of the branch to merge from
          from_branch: master
          # Name of the branch to merge to
          to_branch: deploy_cloudflare 
          # Environment variable containing the token to use for push
          push_token: ${{ secrets.BOT_GITHUB_TOKEN || secrets.GITHUB_TOKEN }}
      - name: Update deploy_digital-ocecan
        # You may pin to the exact commit or the version.
        # uses: bambamboole/gha-upmerge@de87b212278009f9ace0ba024701890b9eb3281b
        uses: bambamboole/gha-upmerge@v1.0.1
        with:
          # Name of the branch to merge from
          from_branch: master
          # Name of the branch to merge to
          to_branch: deploy_digital-ocecan 
          # Environment variable containing the token to use for push
          push_token: ${{ secrets.BOT_GITHUB_TOKEN || secrets.GITHUB_TOKEN }}
      - name: Update deploy_platform-sh
        # You may pin to the exact commit or the version.
        # uses: bambamboole/gha-upmerge@de87b212278009f9ace0ba024701890b9eb3281b
        uses: bambamboole/gha-upmerge@v1.0.1
        with:
          # Name of the branch to merge from
          from_branch: master
          # Name of the branch to merge to
          to_branch: deploy_platform-sh
          # Environment variable containing the token to use for push
          push_token: ${{ secrets.BOT_GITHUB_TOKEN || secrets.GITHUB_TOKEN }}
      - name: Update deploy_render
        # You may pin to the exact commit or the version.
        # uses: bambamboole/gha-upmerge@de87b212278009f9ace0ba024701890b9eb3281b
        uses: bambamboole/gha-upmerge@v1.0.1
        with:
          # Name of the branch to merge from
          from_branch: master
          # Name of the branch to merge to
          to_branch: deploy_render
          # Environment variable containing the token to use for push
          push_token: ${{ secrets.BOT_GITHUB_TOKEN || secrets.GITHUB_TOKEN }}

